doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 80
autodetect: true
pylint:
  options:
    docstring-min-length: 10
    indent-string: "  "
pep8:
  disable:
    - E104
    - E111
