doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 80
autodetect: true
pep8:
  disable:
    - E302
    - E226
    - E41
requirements:
  - requirements.txt
ignore-paths:
  - docs
python-targets:
  - 2
  - 3
